import 'package:flutter/material.dart';

const colorWhite = Colors.white;
const colorBlue = Colors.blue;
const colorBlack = Colors.black;
const colorGrey = Colors.grey;
const colorMineShaft = Color(0xff363636);
const colorAmber = Colors.amber;
const colorParisDaisy = Color(0xffFFEB61);
const colorWildSand = Color(0xffF4F4F4);
const colorDairyCream = Color(0xffF8F0B9);
const colorDawnPink = Color(0xffEBEBEB);
const colorOrange = Color.fromARGB(255, 233, 142, 14);
const colorGreen = Color.fromARGB(255, 14, 233, 58);
const colorMobyDick = Color(0xffDEE8EE);
const colorBackground = Color(0xfff1f7fe);
const colorWildSand2 = Color(0xffF5F5F5);
const colorCodGrey = Color(0xff1D1D1D);
const colorPeach = Color(0xffFFE8B4);
const colorRed = Colors.red;
const colorRedAccent = Colors.redAccent;
const colorBlueAccent = Colors.blueAccent;
const colorpOrange = Color(0xffF87547);
const colorpOBackground = Color(0xffF8F8F8);
const colorWildSand3 = Color.fromARGB(255, 251, 251, 251);
const colorDarkBlue = Color(0xff012269);
const colorLightGrey = Color(0xffBDBDBD);
const colorPink = Color(0xffE95251);
